class SubAudio{constructor(){this.ctx=null;this.mg=null;this.init_=false;this.iv={}}
async init(){if(this.init_)return;try{this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.mg=this.ctx.createGain();this.mg.gain.value=0.25;this.mg.connect(this.ctx.destination);this.init_=true;this._hum();this._creaks();this._sonarLoop();this._water()}catch(e){}}
_hum(){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type='sawtooth';o.frequency.value=38;f.type='lowpass';f.frequency.value=70;g.gain.value=0.1;o.connect(f);f.connect(g);g.connect(this.mg);o.start()}
_creaks(){this.iv.c=setInterval(()=>{if(!this.init_||Math.random()>0.25)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type='sawtooth';o.frequency.value=150+Math.random()*800;f.type='bandpass';f.frequency.value=300+Math.random()*600;f.Q.value=12;g.gain.setValueAtTime(0,this.ctx.currentTime);g.gain.linearRampToValueAtTime(0.035,this.ctx.currentTime+0.04);g.gain.exponentialRampToValueAtTime(0.001,this.ctx.currentTime+0.5);o.connect(f);f.connect(g);g.connect(this.mg);o.start();o.stop(this.ctx.currentTime+1)},6000+Math.random()*8000)}
_sonarLoop(){this.iv.s=setInterval(()=>this.init_&&this.playSonarPing(),14000)}
playSonarPing(){if(!this.init_)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(1400,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(900,this.ctx.currentTime+0.12);g.gain.setValueAtTime(0.1,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(0.001,this.ctx.currentTime+2.5);o.connect(g);g.connect(this.mg);o.start();o.stop(this.ctx.currentTime+3)}
_water(){const b=this.ctx.createBuffer(1,2*this.ctx.sampleRate,this.ctx.sampleRate),d=b.getChannelData(0);let l=0;for(let i=0;i<d.length;i++){d[i]=(l+0.02*(Math.random()*2-1))/1.02;l=d[i];d[i]*=3.5}const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;s.loop=true;f.type='lowpass';f.frequency.value=100;g.gain.value=0.06;s.connect(f);f.connect(g);g.connect(this.mg);s.start()}
playAlarm(){if(!this.init_)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='square';o.frequency.value=480;const n=this.ctx.currentTime;for(let i=0;i<8;i++){g.gain.setValueAtTime(0.15,n+i*0.35);g.gain.setValueAtTime(0,n+i*0.35+0.18)}o.connect(g);g.connect(this.mg);o.start();o.stop(n+3)}
playTorpedoLaunch(){if(!this.init_)return;const b=this.ctx.createBuffer(1,this.ctx.sampleRate*2,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.exp(-i/(this.ctx.sampleRate*0.8));const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=200;f.Q.value=2;g.gain.value=0.3;s.connect(f);f.connect(g);g.connect(this.mg);s.start();const o=this.ctx.createOscillator(),og=this.ctx.createGain();o.type='square';o.frequency.value=120;og.gain.setValueAtTime(0.2,this.ctx.currentTime);og.gain.exponentialRampToValueAtTime(0.001,this.ctx.currentTime+0.15);o.connect(og);og.connect(this.mg);o.start();o.stop(this.ctx.currentTime+0.2)}
playExplosion(){if(!this.init_)return;const b=this.ctx.createBuffer(1,this.ctx.sampleRate*3,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.exp(-i/(this.ctx.sampleRate*0.6))*(1+Math.sin(i/80)*0.3);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=400;g.gain.value=0.5;s.connect(f);f.connect(g);g.connect(this.mg);s.start()}
playMissileLaunch(){if(!this.init_)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(60,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(800,this.ctx.currentTime+1.5);g.gain.setValueAtTime(0.3,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(0.001,this.ctx.currentTime+2);o.connect(g);g.connect(this.mg);o.start();o.stop(this.ctx.currentTime+2.5)}
playClick(){if(!this.init_)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=800;g.gain.setValueAtTime(0.06,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(0.001,this.ctx.currentTime+0.06);o.connect(g);g.connect(this.mg);o.start();o.stop(this.ctx.currentTime+0.08)}
playSwitch(){if(!this.init_)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='square';o.frequency.value=2200;g.gain.setValueAtTime(0.04,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(0.001,this.ctx.currentTime+0.025);o.connect(g);g.connect(this.mg);o.start();o.stop(this.ctx.currentTime+0.04)}
}
export const submarineAudio = new SubAudio()
