import React,{useState,useRef,useEffect,useCallback} from 'react';import{useGameStore,SCENES}from'../../stores/gameStore';import{runSceneDialogue,indraVoice}from'../../systems/AIAssistant';import{submarineAudio}from'../../systems/AudioManager'
export default function BiometricPanel({visible}){const[phase,setPhase]=useState('waiting');const[prog,setProg]=useState(0);const ref=useRef();const auth=useGameStore(s=>s.captainAuthenticated);const doAuth=useGameStore(s=>s.authenticateCaptain);const setScene=useGameStore(s=>s.setScene);const scene=useGameStore(s=>s.currentScene)
const drawFP=useCallback((ctx,w,h,p)=>{ctx.clearRect(0,0,w,h);ctx.fillStyle='rgba(0,4,16,0.97)';ctx.fillRect(0,0,w,h);const cx=w/2,cy=h/2;for(let i=0;i<18;i++){if(i/18>p)break;ctx.strokeStyle=`rgba(0,229,255,${0.12+(p>i/18?0.3:0)})`;ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(cx+Math.sin(i*0.8)*4,cy+i*1.5,14+i*6*0.7,14+i*6,i*0.15,0,Math.PI*2);ctx.stroke()};if(phase==='scanning'){const sy=cy-70+p*140;const g=ctx.createLinearGradient(0,sy-4,0,sy+4);g.addColorStop(0,'transparent');g.addColorStop(0.5,'rgba(255,153,51,0.7)');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(cx-80,sy-3,160,6)};if(phase==='verified'){ctx.fillStyle='rgba(0,230,118,0.1)';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#00e676';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx-20,cy+5);ctx.lineTo(cx-5,cy+20);ctx.lineTo(cx+25,cy-15);ctx.stroke()}},[phase])
useEffect(()=>{const cv=ref.current;if(!cv)return;drawFP(cv.getContext('2d'),cv.width,cv.height,prog)},[prog,phase,drawFP])
const startScan=useCallback(()=>{if(phase!=='waiting'||auth)return;submarineAudio.init();submarineAudio.playClick();setPhase('scanning');let p=0;const iv=setInterval(()=>{p+=0.02;setProg(p);if(p>=1){clearInterval(iv);setPhase('verified');doAuth();indraVoice.speak("Biometric confirmed. Captain authenticated. Jai Hind. Welcome aboard INS Arihant.",'normal');setTimeout(()=>{setScene(SCENES.SYSTEMS_CHECK);runSceneDialogue(SCENES.SYSTEMS_CHECK)},2500)}},30)},[phase,auth,doAuth,setScene])
if(!visible||(scene!==SCENES.BOOT&&scene!==SCENES.AUTH&&auth))return null
return<div style={{position:'fixed',inset:0,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(0,2,10,0.97)',zIndex:200,fontFamily:'var(--font-ui)'}}>
<div style={{width:340,background:'rgba(0,8,20,0.96)',border:'1px solid rgba(0,229,255,0.15)',borderRadius:8,padding:30,textAlign:'center'}}>
<div style={{display:'flex',marginBottom:16,borderRadius:4,overflow:'hidden'}}><div style={{flex:1,height:4,background:'#FF9933'}}/><div style={{flex:1,height:4,background:'#FFF'}}/><div style={{flex:1,height:4,background:'#138808'}}/></div>
<div style={{fontFamily:'var(--font-display)',fontSize:13,color:'var(--hud-primary)',letterSpacing:4,marginBottom:2}}>INS ARIHANT</div>
<div style={{fontSize:10,color:'rgba(176,190,197,0.4)',letterSpacing:2,marginBottom:6}}>NUCLEAR SUBMARINE S73</div>
<div style={{fontSize:9,color:'rgba(176,190,197,0.3)',letterSpacing:1,marginBottom:20}}>INDIAN NAVY — CAPTAIN AUTHENTICATION</div>
<div onClick={startScan} style={{width:180,height:180,margin:'0 auto 18px',cursor:phase==='waiting'?'pointer':'default',border:`2px solid ${phase==='verified'?'#00e676':'rgba(0,229,255,0.2)'}`,borderRadius:'50%',overflow:'hidden',transition:'all 0.5s',boxShadow:phase==='scanning'?'0 0 30px rgba(255,153,51,0.2)':phase==='verified'?'0 0 30px rgba(0,230,118,0.2)':'none'}}><canvas ref={ref} width={180} height={180}/></div>
<div style={{fontFamily:'var(--font-mono)',fontSize:10,color:phase==='verified'?'#00e676':phase==='scanning'?'#FF9933':'rgba(176,190,197,0.5)',letterSpacing:1,animation:phase==='scanning'?'pulse-glow 1s infinite':'none'}}>{phase==='waiting'&&'PLACE HAND ON SCANNER'}{phase==='scanning'&&('SCANNING... '+Math.round(prog*100)+'%')}{phase==='verified'&&'✓ JAI HIND, CAPTAIN'}</div>
<div style={{marginTop:14,fontSize:9,color:'rgba(176,190,197,0.2)',letterSpacing:1}}>शं नो वरुणः</div>
</div></div>}
